### ISSUE TITLE
Issue-add styles for tabs

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#103]
Automated Review Comments
Issues in index.html:
  - (4, 'Hardcoded string found')
Issues in src/main.js:
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')

**Comment by jamesleeksc** [comment]
I got it.
