### ISSUE TITLE
Issue-add examples folder

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#109]
Automated Review Comments
Issues in examples/barChartExample/.babelrc:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in examples/barChartExample/.eslintrc.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in examples/barChartExample/components/Picker.js:
  - (2, 'Hardcoded string found')
Issues in examples/barChartExample/components/Posts.js:
  - (2, 'Hardcoded string found')
Issues in examples/barChartExample/containers/App.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in examples/barChartExample/index.html:
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in examples/barChartExample/index.js:
  - (3, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in examples/barChartExample/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in examples/barChartExample/reducers/index.js:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in examples/barChartExample/server.js:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in examples/barChartExample/store/configureStore.js:
  - (2, 'Hardcoded string found')
Issues in examples/barChartExample/webpack.config.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
