### ISSUE TITLE
Issue-move to separate folder for each example

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#111]
Automated Review Comments
Issues in examples/barChartExample/components/Axis.js:
  - (2, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
Issues in examples/barChartExample/components/AxisTick.js:
  - (2, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
Issues in examples/barChartExample/components/Bar.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
Issues in examples/barChartExample/components/Example.js:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
Issues in examples/barChartExample/components/common/Container.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in examples/barChartExample/containers/App.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
Issues in examples/barChartExample/data/states_by_age.js:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (565, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (579, 'Hardcoded string found')
  - (592, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (634, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (648, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (677, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (691, 'Hardcoded string found')
  - (704, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
Issues in examples/barChartExample/index.html:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (322, 'Line exceeds 80 characters')
  - (328, 'Line exceeds 80 characters')
  - (485, 'Line exceeds 80 characters')
  - (643, 'Line exceeds 80 characters')
  - (801, 'Line exceeds 80 characters')
  - (966, 'Hardcoded string found')
  - (1012, 'Hardcoded string found')
Issues in examples/barChartExample/index.js:
  - (1, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in examples/barChartExample/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in examples/barChartExample/reducers/exampleReducer.js:
  - (25, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
Issues in examples/barChartExample/reducers/index.js:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in examples/barChartExample/server.js:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
Issues in examples/barChartExample/store.js:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
Issues in examples/barChartExample/utils.js:
  - (50, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
Issues in examples/barChartExample/webpack.prod.config.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (23, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
