### ISSUE TITLE
Issue-move bar chart to examples folder

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#113]
Automated Review Comments
Issues in examples/barChartExample/.babelrc:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in examples/barChartExample/index.html:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (325, 'Line exceeds 80 characters')
  - (331, 'Line exceeds 80 characters')
  - (488, 'Line exceeds 80 characters')
  - (646, 'Line exceeds 80 characters')
  - (804, 'Line exceeds 80 characters')
  - (969, 'Hardcoded string found')
  - (1015, 'Hardcoded string found')
  - (1025, 'Hardcoded string found')
  - (1027, 'Hardcoded string found')
Issues in examples/barChartExample/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in examples/barChartExample/src/actions/exampleActions.js:
  - (56, 'Hardcoded string found')
Issues in examples/barChartExample/src/components/Axis.js:
  - (2, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
Issues in examples/barChartExample/src/components/AxisTick.js:
  - (2, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
Issues in examples/barChartExample/src/components/Bar.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
Issues in examples/barChartExample/src/components/Example.js:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
Issues in examples/barChartExample/src/components/common/Container.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in examples/barChartExample/src/data/states_by_age.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (471, 'Hardcoded string found')
  - (472, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (497, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (510, 'Hardcoded string found')
  - (511, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (563, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (615, 'Hardcoded string found')
  - (627, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (640, 'Hardcoded string found')
  - (641, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
Issues in examples/barChartExample/src/main.js:
  - (3, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
Issues in examples/barChartExample/src/reducers/exampleReducer.js:
  - (55, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
Issues in examples/barChartExample/src/reducers/index.js:
  - (2, 'Hardcoded string found')
Issues in examples/barChartExample/src/store.js:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
Issues in examples/barChartExample/src/utils.js:
  - (50, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
Issues in examples/barChartExample/webpack.config.js:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (39, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
