### ISSUE TITLE
Issue-improvements to axis animations

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#115]
Automated Review Comments
Issues in examples/barChartExample/src/components/Axis.js:
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in examples/barChartExample/src/components/AxisTick.js:
  - (1, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
Issues in examples/barChartExample/src/main.js:
  - (1, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (33, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
