### ISSUE TITLE
Issue-add github banner

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#121]
Automated Review Comments
Issues in examples/barChartExample/src/main.js:
  - (1, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
