### ISSUE TITLE
Issue-switch order of sliders and tweak text

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#123]
Automated Review Comments
Issues in examples/barChartExample/src/components/Example.js:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
