### ISSUE TITLE
Issue-update dependencies - remove non-essential libs

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#127]
Automated Review Comments
Issues in examples/barChartExample/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
