### ISSUE TITLE
Issue-formatting/file clean up

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#129]
Automated Review Comments
Issues in examples/barChartExample/index.html:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
