### ISSUE TITLE
Issue-add production webpack file

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#145]
Automated Review Comments
Issues in examples/barChartExample/webpack.prod.config.js:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')

**Comment by jamesleeksc** [comment]
I got it.
