### ISSUE TITLE
Issue-add code for alphabet example

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#153]
Automated Review Comments
Issues in examples/alphabetExample/.eslintrc.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in examples/alphabetExample/index.html:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in examples/alphabetExample/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in examples/alphabetExample/src/components/DataGenerator.js:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in examples/alphabetExample/src/components/Text.js:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
Issues in examples/alphabetExample/src/components/common/Container.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in examples/alphabetExample/src/components/index.js:
  - (2, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
Issues in examples/alphabetExample/src/main.js:
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in examples/alphabetExample/src/reducers/exampleReducer.js:
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in examples/alphabetExample/src/reducers/index.js:
  - (2, 'Hardcoded string found')
Issues in examples/alphabetExample/src/store.js:
  - (2, 'Hardcoded string found')
Issues in examples/alphabetExample/webpack.config.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in examples/alphabetExample/webpack.prod.config.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')

**Comment by ksfactor** [comment]
I got it.
