### ISSUE TITLE
Issue-updates to alphabet example

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#155]
Automated Review Comments
Issues in examples/alphabetExample/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in examples/alphabetExample/src/components/Chart.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in examples/alphabetExample/src/components/index.js:
  - (2, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
Issues in examples/alphabetExample/src/css/bootstrap.grid.css:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (334, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (497, 'Line exceeds 80 characters')
  - (655, 'Line exceeds 80 characters')
  - (813, 'Line exceeds 80 characters')
  - (978, 'Hardcoded string found')
Issues in examples/alphabetExample/src/main.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in examples/barChartExample/src/main.js:
  - (6, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
