### ISSUE TITLE
Issue-working on data generation with time stamps

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#165]
Automated Review Comments
Issues in examples/streamGraphExample/src/data/index.js:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/reducers/utils.js:
  - (2, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (83, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
