### ISSUE TITLE
Issue-add seletectable filters for series

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#181]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/index.js:
  - (1, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/reducers/exampleReducer.js:
  - (53, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (199, 'Line exceeds 80 characters')

**Comment by jamesleeksc** [comment]
I got it.
