### ISSUE TITLE
Issue-add d3-time format, redux logger, lock version of moment

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#183]
Automated Review Comments
Issues in examples/streamGraphExample/package.json:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
