### ISSUE TITLE
Issue-workinf on reducer - dates on axis working

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#191]
Automated Review Comments
Issues in examples/streamGraphExample/src/reducers/exampleReducer.js:
  - (25, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
Issues in examples/streamGraphExample/src/reducers/utils.js:
  - (2, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
