### ISSUE TITLE
Issue-add Path component

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#195]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/Path.js:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (98, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
