### ISSUE TITLE
Issue-mounting of paths working

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#197]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/index.js:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
Issues in examples/streamGraphExample/src/reducers/exampleReducer.js:
  - (35, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')

**Comment by ksfactor** [comment]
I got it.
