### ISSUE TITLE
Issue-add webpack config

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#20]
Automated Review Comments
Issues in webpack.config.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (26, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
