### ISSUE TITLE
Issue-add styles to path nodes

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#205]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/Path.js:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (65, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
