### ISSUE TITLE
Issue-add radio buttons for offsset

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#207]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/index.js:
  - (41, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
