### ISSUE TITLE
Issue-add ability to change offset

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#209]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/index.js:
  - (8, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/reducers/exampleReducer.js:
  - (21, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
Issues in examples/streamGraphExample/src/reducers/utils.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
