### ISSUE TITLE
Issue-tweaks to transitions between offsets

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#211]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/Path.js:
  - (6, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/components/index.js:
  - (19, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/reducers/exampleReducer.js:
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
