### ISSUE TITLE
Issue-set opacity when mounting, not in render

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#213]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/Path.js:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
