### ISSUE TITLE
Issue-re-format top of page/add text

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#217]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/index.js:
  - (1, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
