### ISSUE TITLE
Issue-add initital source components

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#22]
Automated Review Comments
Issues in src/components/DataGenerator.js:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/components/Text.js:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
Issues in src/components/common/Container.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in src/components/index.js:
  - (2, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
Issues in src/main.js:
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in src/reducers/exampleReducer.js:
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in src/reducers/index.js:
  - (2, 'Hardcoded string found')
Issues in src/store.js:
  - (2, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
