### ISSUE TITLE
Issue-add containers folder for connected components

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#233]
Automated Review Comments
Issues in examples/streamGraphExample/src/containers/Example.js:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/main.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (32, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
