### ISSUE TITLE
Issue-add y axis

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#241]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/YAxis.js:
  - (2, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/components/YAxisTick.js:
  - (2, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/containers/Example.js:
  - (30, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/reducers/index.js:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
