### ISSUE TITLE
Issue-use switch statements for receive props on axes

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#243]
Automated Review Comments
Issues in examples/streamGraphExample/src/components/XAxisTick.js:
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/components/YAxisTick.js:
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
