### ISSUE TITLE
Issue-switch to 0.15 material-ui

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#247]
Automated Review Comments
Issues in examples/alphabetExample/package.json:
  - (7, 'Hardcoded string found')
Issues in examples/barChartExample/package.json:
  - (7, 'Hardcoded string found')
Issues in examples/streamGraphExample/package.json:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
