### ISSUE TITLE
Issue-remove button for reloading

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#251]
Automated Review Comments
Issues in examples/streamGraphExample/src/containers/Example.js:
  - (5, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
