### ISSUE TITLE
Issue-remove link buttons in footer

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#261]
Automated Review Comments
Issues in examples/streamGraphExample/src/containers/Example.js:
  - (1, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (36, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
