### ISSUE TITLE
Issue-adjust margins and make Example the root component

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#267]
Automated Review Comments
Issues in examples/barChartExample/src/components/index.js:
  - (3, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in examples/barChartExample/src/main.js:
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (28, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
