### ISSUE TITLE
Issue-update action names and root component

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#277]
Automated Review Comments
Issues in examples/barChartExample/src/containers/index.js:
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in examples/barChartExample/src/reducers/index.js:
  - (8, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in examples/streamGraphExample/src/containers/index.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (129, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
Issues in examples/streamGraphExample/src/main.js:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in examples/streamGraphExample/webpack.config.js:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
