### ISSUE TITLE
Issue-accepts scale0 and scale0 props/use yHeight

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#281]
Automated Review Comments
Issues in examples/barChartExample/src/components/AxisTick.js:
  - (1, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (80, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
