### ISSUE TITLE
Issue-updated nocred api

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#35]
Automated Review Comments
Issues in packages/app/config/env.js:
  - (4, 'Hardcoded string found')
Issues in packages/app/package.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in packages/app/pages/[url_id].jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in packages/app/pages/api/config/redis.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in packages/app/pages/api/helper/index.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in packages/extension/popup.js:
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in yarn.lock:
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (173, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (196, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (217, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (241, 'Line exceeds 80 characters')
  - (242, 'Line exceeds 80 characters')
  - (244, 'Hardcoded string found')
  - (249, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (279, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (302, 'Line exceeds 80 characters')
  - (303, 'Line exceeds 80 characters')
  - (309, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (328, 'Line exceeds 80 characters')
  - (329, 'Line exceeds 80 characters')
  - (333, 'Line exceeds 80 characters')
  - (334, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (341, 'Line exceeds 80 characters')
  - (343, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (352, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (360, 'Line exceeds 80 characters')
  - (364, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (369, 'Line exceeds 80 characters')
  - (370, 'Line exceeds 80 characters')
  - (377, 'Line exceeds 80 characters')
  - (378, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (383, 'Line exceeds 80 characters')
  - (389, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (401, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (413, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (418, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (422, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (427, 'Line exceeds 80 characters')
  - (428, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (437, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (451, 'Line exceeds 80 characters')
  - (452, 'Line exceeds 80 characters')
  - (456, 'Line exceeds 80 characters')

**Comment by ksfactor** [comment]
I got it.
