### ISSUE TITLE
Issue-basic reducer for example working/data loading

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#52]
Automated Review Comments
Issues in src/actions/exampleActions.js:
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
Issues in src/components/Example.js:
  - (2, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
Issues in src/main.js:
  - (2, 'Hardcoded string found')
Issues in src/reducers/exampleReducer.js:
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
Issues in src/store.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
Issues in src/utils.js:
  - (3, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (225, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
