### ISSUE TITLE
Issue-add bar component

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#54]
Automated Review Comments
Issues in src/components/Bar.js:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
