### ISSUE TITLE
Issue-update dependencies/add .gitignore

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#6]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
