### ISSUE TITLE
Issue-update dependencies

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#62]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (21, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
