### ISSUE TITLE
Issue-add opacity to bars and start mounts from same positions

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#68]
Automated Review Comments
Issues in src/components/Bar.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
