### ISSUE TITLE
Issue-animate location of percent text on update

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#70]
Automated Review Comments
Issues in src/components/Bar.js:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
