### ISSUE TITLE
Issue-switch to material ui table

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#72]
Automated Review Comments
Issues in index.html:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in src/components/Bar.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in src/components/Example.js:
  - (4, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
Issues in src/components/common/Container.js:
  - (6, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in src/main.js:
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (36, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
