### ISSUE TITLE
Issue-use material ui card for containing bar chart example

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#76]
Automated Review Comments
Issues in src/components/Bar.js:
  - (1, 'Line exceeds 80 characters')
Issues in src/components/Example.js:
  - (3, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in src/main.js:
  - (4, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
