### ISSUE TITLE
Issue-separate functions for mounting, updating, and removing

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#78]
Automated Review Comments
Issues in src/components/Bar.js:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (122, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
