### ISSUE TITLE
Issue-use node instead of data to avoid confusion

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#84]
Automated Review Comments
Issues in src/components/Bar.js:
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
