### ISSUE TITLE
Issue-remove size from returned node

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#85]
Automated Review Comments
Issues in src/components/Bar.js:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
Issues in src/utils.js:
  - (16, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
