### ISSUE TITLE
Issue-add axis and axis ticks

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#93]
Automated Review Comments
Issues in src/components/Axis.js:
  - (2, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in src/components/AxisTick.js:
  - (2, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')

**Comment by jamesleeksc** [comment]
I got it.
