### ISSUE TITLE
Issue-transitions for axis ticks

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#95]
Automated Review Comments
Issues in src/components/Axis.js:
  - (2, 'Hardcoded string found')
Issues in src/components/AxisTick.js:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
Issues in src/components/Example.js:
  - (1, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')

**Comment by ksfactor** [comment]
I got it.
