### ISSUE TITLE
Issue-tweaks to axis tick animations

### ISSUE THREAD

**Issue by primcoder1020** [primcoder1020/d3-transitions#97]
Automated Review Comments
Issues in src/components/AxisTick.js:
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')

**Comment by ksfactor** [comment]
I got it.
